name: deploy_python_flask

on: [push]

env:
  AZURE_WEBAPP_NAME: pythonappiba # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.11" # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python ${{ env.PYTHON_VERSION  }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION}}

      - name: "Resolve Project requirements Using pip"
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deploy to Azure Web apps
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
